### ISSUE TITLE
Some strange issue with starting Docker

### ISSUE THREAD

**Issue by szibis** [kpine/zwave-js-server-docker#1] opened 2021-03-27 22:43 UTC
I try from inside of docker and with docker run but always same effect:

```
zwave-server --config options.js  /dev/zwave


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7eedd15c
Illegal instruction (core dumped)
```

options.js
```
module.exports = {
  logConfig: {
    filename: process.env.LOGFILENAME,
  },

  storage: {
    cacheDir: "/cache",
  },

  networkKey: process.env.NETWORK_KEY,
};
```
env variablees
```
echo $NETWORK_KEY
94949494949494949494949494949494
echo $LOGFILENAME
/logs/zwave.log
```
directories exist
```
 ls -la /cache/
total 8
drwxr-xr-x    2 root     root          4096 Mar  3  2021 .
drwxr-xr-x    1 root     root          4096 Mar 27  2021 ..
/app # ls -la /logs/
total 8
drwxr-xr-x    2 root     root          4096 Mar  3  2021 .
drwxr-xr-x    1 root     root          4096 Mar 27  2021 ..
```
Also /dev/zwave llinked
```
ls -la /dev/zwave
crw-rw----    1 root     dialout   166,   0 Mar 27  2021 /dev/zwave
```

Anything that can help me debug this ??

**Comment by kpine** [comment] 2021-03-28 03:31
What platform are you running on? Did you build the image yourself?

**Comment by szibis** [comment] 2021-03-28 07:24
image is 
```
kpine/zwave-js-server:latest
```
And OS
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

**Comment by kpine** [comment] 2021-03-28 16:09
Which RPi3 are you using? I've tried the image on all three platforms that it's published for, and they all worked OK for me. Does the architecture of the image match your OS arch?

RPi4:
```
$ uname -a
Linux rpi2 5.10.17-v8+ #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021 aarch64 GNU/Linux
$ sudo docker inspect -f "{{ .Architecture }}" kpine/zwave-js-server:latest
arm64
```
RPi3:
```
$ uname -a
Linux rpi1 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
$ sudo docker inspect -f "{{ .Architecture }}" kpine/zwave-js-server:latest
arm
```
x64:
```
$ uname -a
Linux dev 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
$ sudo docker inspect -f "{{ .Architecture }}" kpine/zwave-js-server:latest
amd64
```

I suppose that error is coming from nodejs. I don't think I'm going to be much help with that. You might try building the image directly on your RPi. Or, installing nodejs directly and see if that works.

**Comment by szibis** [comment] 2021-03-28 19:40
```
uname --a
Linux hass 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux
```
```
sudo docker inspect -f "{{ .Architecture }}" kpine/zwave-js-server:latest
arm
```
I just set today https://github.com/zwave-js/zwavejs2mqtt from Docker and all is working there without any issues.

Yes looks like this is error from node itself and tried to debug this from inside the container shell but I am not very familiar with Node. I would like to not pollute my OS with Node with all this modules if I can choose docker. 

I can close this as zwavejs2mqtt works for me and do what I need, still this is strange issue.

**Comment by kpine** [comment] 2021-04-09 18:43
I'll go ahead and close this. It's possible there's something wrong with how the Docker Hub images are built. I'm using buildx for cross compiling , except I can't reproduce it on the same hardware myself (rpi3 and 4), and don't have the means to debug it.

**Closed by kpine** 2021-04-09 18:43 UTC

**Comment by imposibrus** [comment] 2021-06-29 15:06
Same behaviour on Raspberry 4b, Raspbian 10, `Linux raspberrypi 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux`.

Building image locally helps, though! Thanks!

**Comment by kpine** [comment] 2021-07-05 17:42
What version of docker and what version of `libseccomp`? Since these images are based on Alpine 3.13, for 32-bit ARM OS (armhf/armv7) it sounds like Docker version 19.03.9 or later and `libseccomp` version 2.42 or later are both required.

On my RPi3 I am using Docker CE 20.10.7 and libseccomp 2.4.4-1~bpo10+1 (from Debian Buster backports).

**Comment by imposibrus** [comment] 2021-07-06 08:09
You are right, @kpine, the reason was the version of `libseccomp2`.

```
> docker version

Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:58:04 2021
 OS/Arch:           linux/arm
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:56:06 2021
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

```
> dpkg -l | grep libseccomp
libseccomp2:armhf              2.3.3-4

> apt-cache madison libseccomp2
libseccomp2 |    2.3.3-4 | http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```
Version is old👆 and it is not from the backports. So i decided to add the backports repo:

```
> echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee /etc/apt/sources.list.d/backports.list
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 648ACFD622F3D138
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC
> sudo apt-get update
```
After this new version are available:
```
> apt-cache madison libseccomp2
libseccomp2 | 2.4.4-1~bpo10+1 | http://deb.debian.org/debian buster-backports/main armhf Packages
libseccomp2 |    2.3.3-4 | http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
```
Install version from the backports:
```
sudo apt-get install -t buster-backports libseccomp2
```

After that, switch from local-builded image back to `kpine/zwave-js-server:1.8.0-7.10.0` and it works!
So, new version of `libseccomp` - is Alpine dependency?

**Comment by kpine** [comment] 2021-07-06 14:14
Not just Alpine, other distributions affected as well. https://github.com/moby/moby/issues/40734

[Alpine 3.13 release notes](https://wiki.alpinelinux.org/w/index.php?title=Release_Notes_for_Alpine_3.13.0&oldid=19609#time64_requirements) also mention it, with some alternate fixes.
